//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Settrix.Comunication.Resources.Company {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Settrix.Comunication.Resources.Company.CompanyResource", typeof(CompanyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NAME_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("NAME_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        public static string INVALID_CNPJ {
            get {
                return ResourceManager.GetString("INVALID_CNPJ", resourceCulture);
            }
        }
        
        public static string UNSUPPORTED_COMPANY_FUNCTION {
            get {
                return ResourceManager.GetString("UNSUPPORTED_COMPANY_FUNCTION", resourceCulture);
            }
        }
        
        public static string CNPJ_ALREADY_USED {
            get {
                return ResourceManager.GetString("CNPJ_ALREADY_USED", resourceCulture);
            }
        }
    }
}
